### PR TITLE
Initialize Amplitude SDK though instrumentor script

### PR DESCRIPTION
**Pull request by weotch**
This approach matches other sites in it’s use of GTM and instrumentor scripts.

### CODE REVIEW

**Review by Sierangho — APPROVED** [review]

**Comment by Sierangho** [comment]
i assume it just works

**Comment by weotch** [comment]
Thanks @Sierangho!  Does this trigger a deploy?  Or, do you know when this will be deployed to https://datanomgame.com?  I just want to sanity check that everything is working.

**Comment by Sierangho** [comment]
i uploaded the files to s3 - should be updated 
https://com-amplitude-games.s3-us-west-2.amazonaws.com/pacman/index.htm 
(I think the datanomgame.com points to that)

**Comment by weotch** [comment]
I don't see https://datanomgame.com/ updated though I do see the updated code on that S3 URL.  One way to test is that there should be a GTM embed code in the `<head>`.

https://github.com/amplitude/demo-games/blob/c1be0eff4244f40ce03b4d0ec0b8ea5901976f40/pacman/index.htm#L56-L62

**Comment by Sierangho** [comment]
I actually have no idea how datanomgame.com was/is deployed 
@kelsonpw  would you know?

**Pull request merged**
